/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AgentEmailForm: typeof import('./src/components/AgentEmailForm.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ContractList: typeof import('./src/components/ContractList.vue')['default']
    ContractProgressCard: typeof import('./src/components/ContractProgressCard.vue')['default']
    ContractSummaryCard: typeof import('./src/components/ContractSummaryCard.vue')['default']
    CustomStepper: typeof import('./src/components/CustomStepper.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocumentChecklist: typeof import('./src/components/DocumentChecklist.vue')['default']
    DocumentUploadList: typeof import('./src/components/DocumentUploadList.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmailSendAnimation: typeof import('./src/components/EmailSendAnimation.vue')['default']
    EtchSignIFrame: typeof import('./src/components/EtchSignIFrame.vue')['default']
    FillContract: typeof import('./src/components/FillContract.vue')['default']
    GoToFormsCard: typeof import('./src/components/GoToFormsCard.vue')['default']
    GoToQuestionsCard: typeof import('./src/components/GoToQuestionsCard.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    PropertyImageGallery: typeof import('./src/components/PropertyImageGallery.vue')['default']
    QuestionFlow: typeof import('./src/components/QuestionFlow.vue')['default']
    QuestionInput: typeof import('./src/components/QuestionInput.vue')['default']
    ReferralButton: typeof import('./src/components/ReferralButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionProgressBar: typeof import('./src/components/SectionProgressBar.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SignContract: typeof import('./src/components/SignContract.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TooltipPopover: typeof import('./src/components/TooltipPopover.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
