export interface IPDFField {
  id: string;
  name: string;
  type: string;
  pageNum: number;
  rect?: {
    x: number;
    y: number;
    height: number;
    width: number;
  };
  children?: any[];
}

export const all2017Fields: IPDFField[] = [
  {
    id: "sellerName",
    name: "1A Seller Name",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 279,
      y: 94,
      height: 10,
      width: 277,
    },
  },
  {
    id: "buyerName",
    name: "1A Buyer Name",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 123,
      y: 104,
      height: 10,
      width: 391,
    },
  },
  {
    id: "propertyLot",
    name: "2A Lot",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 127,
      y: 169,
      height: 9,
      width: 66,
    },
  },
  {
    id: "propertyBlock",
    name: "2A Block",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 222,
      y: 168,
      height: 10,
      width: 83,
    },
  },
  {
    id: "propertyAddition",
    name: "2A Addition",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 309,
      y: 167,
      height: 10,
      width: 247,
    },
  },
  {
    id: "propertyCity",
    name: "2A City Name",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 157,
      y: 177,
      height: 10,
      width: 171,
    },
  },
  {
    id: "propertyCounty",
    name: "2A County Name",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 387,
      y: 179,
      height: 9,
      width: 169,
    },
  },
  {
    id: "propertyFullAddress",
    name: "2A Full Property Address",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 161,
      y: 189,
      height: 9,
      width: 395,
    },
  },
  {
    id: "retainedImprovementsLine1",
    name: "2D Improvements and accessories to be retained line 1",
    type: "textWrap",
    pageNum: 0,
    children: [
      {
        name: "Line 1 - 2D Improvements and accessories to be retained line 1",
        rect: {
          x: 322,
          y: 400,
          height: 12,
          width: 233,
        },
      },
      {
        name: "Line 2 - 2D Improvements and accessories to be retained line 1",
        rect: {
          x: 73,
          y: 412,
          height: 13,
          width: 481,
        },
      },
    ],
  },
  {
    id: "amount3A",
    name: "3A Amount",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 457,
      y: 466,
      height: 9,
      width: 101,
    },
  },
  {
    id: "cbThirdPartyAddendumAttached",
    name: "3B Third Party Financing Addendum Attached",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 315,
      y: 500,
      height: 9,
      width: 8,
    },
  },
  {
    id: "cbLoanAssumptionAddendumAttached",
    name: "3B Loan Assumption Addendum Attached",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 76,
      y: 513,
      height: 10,
      width: 9,
    },
  },
  {
    id: "cbSellerFinancingAddendumAttached",
    name: "3B Seller Financing Addendum Attached",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 249,
      y: 513,
      height: 10,
      width: 11,
    },
  },
  {
    id: "amount3B",
    name: "3B Amount",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 457,
      y: 515,
      height: 9,
      width: 101,
    },
  },
  {
    id: "amount3C",
    name: "3C Amount",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 457,
      y: 527,
      height: 9,
      width: 101,
    },
  },
  {
    id: "cbResidentialLeaseAddendumAttached",
    name: "4A Addendum Regarding Residential Leases",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 49,
      y: 588,
      height: 9,
      width: 8,
    },
  },
  {
    id: "cbFixtureLeaseAddendumAttached",
    name: "4B Addendum Regarding Fixture Leases",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 49,
      y: 612,
      height: 9,
      width: 9,
    },
  },
  {
    id: "cbNaturalResourceAddendumAttached",
    name: "4C Natural Resource Leases",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 50,
      y: 648,
      height: 9,
      width: 9,
    },
  },
  {
    id: "cbNaturalResourceAddendumDeliveredToBuyer",
    name: "4C(1) Seller has delivered to Buyer a copy of the Natural Resource Leases",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 61,
      y: 684,
      height: 9,
      width: 11,
    },
  },
  {
    id: "cbNaturalResourceAddendumNotDeliveredToBuyer",
    name: "4C(2) Seller has not delivered to Buyer a copy of all the Natural Resource Leases",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 62,
      y: 699,
      height: 9,
      width: 9,
    },
  },
  {
    id: "cbNaturalResourceAddendumDaysToDeliver",
    name: "4C(2) Number of days",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 337,
      y: 723,
      height: 9,
      width: 36,
    },
  },
  {
    id: "buyer1InitialPage122",
    name: "Buyer 1 Initial Page 1",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 211,
      y: 762,
      height: 9,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage123",
    name: "Buyer 2 Initial Page 1",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 252,
      y: 762,
      height: 9,
      width: 36,
    },
  },
  {
    id: "seller1InitialPage124",
    name: "Seller 1 Initial Page 1",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 347,
      y: 762,
      height: 9,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage125",
    name: "Seller 2 Initial Page 1",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 396,
      y: 762,
      height: 9,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage2",
    name: "Address of Property Page 2",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 128,
      y: 30,
      height: 12,
      width: 326,
    },
  },
  {
    id: "escrowAgentName",
    name: "5A Escrow Agent",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 153,
      y: 83,
      height: 10,
      width: 153,
    },
  },
  {
    id: "titleCompanyNameAddress",
    name: "5A Title Company Name Address",
    type: "textWrap",
    pageNum: 1,
    children: [
      {
        name: "Line 1 - 5A Title Company Name Address",
        rect: {
          x: 404,
          y: 82,
          height: 11,
          width: 158,
        },
      },
      {
        name: "Line 2 - 5A Title Company Name Address",
        rect: {
          x: 76,
          y: 94,
          height: 9,
          width: 151,
        },
      },
    ],
  },
  {
    id: "escrowEarnestMoney",
    name: "5A Amount (Earnest Money)",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 293,
      y: 93,
      height: 10,
      width: 72,
    },
  },
  {
    id: "escrowOptionFee",
    name: "5A Amount (Option Fee)",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 488,
      y: 93,
      height: 10,
      width: 75,
    },
  },
  {
    id: "escrowAdditionalEarnestMoney",
    name: "5A(1) Amount",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 342,
      y: 125,
      height: 11,
      width: 106,
    },
  },
  {
    id: "escrowAdditionalEarnestMoneyDaysToDeliver",
    name: "5A(1) Number of Days",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 94,
      y: 137,
      height: 9,
      width: 36,
    },
  },
  {
    id: "optionPeriodDays",
    name: "5B Number of Days",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 76,
      y: 282,
      height: 10,
      width: 38,
    },
  },
  {
    id: "cbTitlePolicyIsSellerExpense",
    name: "6A Seller expense",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 314,
      y: 432,
      height: 8,
      width: 8,
    },
  },
  {
    id: "cbTitlePolicyIsBuyerExpense",
    name: "6A Buyer expense",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 369,
      y: 431,
      height: 9,
      width: 9,
    },
  },
  {
    id: "titleCompanyName",
    name: "6A Name of Title Company",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 285,
      y: 443,
      height: 9,
      width: 200,
    },
  },
  {
    id: "cbTitlePolicyWillNotBeAmended",
    name: "6A(8)(i) will not be amended",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 76,
      y: 604,
      height: 9,
      width: 9,
    },
  },
  {
    id: "cbTitlePolicyWillBeAmended",
    name: "6A(8)(ii) will be amended",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 77,
      y: 615,
      height: 9,
      width: 8,
    },
  },
  {
    id: "cbTitleAmendedAtBuyerExpense",
    name: "6A(8)ii Buyer Expense",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 435,
      y: 616,
      height: 8,
      width: 11,
    },
  },
  {
    id: "cbTitleAmendedAtSellerExpense",
    name: "6A(8)ii Seller Expense",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 499,
      y: 616,
      height: 8,
      width: 11,
    },
  },
  {
    id: "buyer1InitialPage242",
    name: "Buyer 1 Initial Page 2",
    type: "initial",
    pageNum: 1,
    rect: {
      x: 211,
      y: 759,
      height: 12,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage243",
    name: "Buyer 2 Initial Page 2",
    type: "initial",
    pageNum: 1,
    rect: {
      x: 253,
      y: 759,
      height: 12,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage244",
    name: "Seller 1 Initial Page 2",
    type: "initial",
    pageNum: 1,
    rect: {
      x: 347,
      y: 759,
      height: 11,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage245",
    name: "Seller 2 Initial Page 2",
    type: "initial",
    pageNum: 1,
    rect: {
      x: 396,
      y: 759,
      height: 11,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage3",
    name: "Address of Property Page 3",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 131,
      y: 29,
      height: 14,
      width: 324,
    },
  },
  {
    id: "cbSurveySellerExisting",
    name: "6C(1) Checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 58,
      y: 76,
      height: 10,
      width: 12,
    },
  },
  {
    id: "surveySellerExistingDaysToDeliver",
    name: "6C(1) Number of Days",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 125,
      y: 77,
      height: 10,
      width: 37,
    },
  },
  {
    id: "cbSurveySellerExistingReplacementSellerExpense",
    name: "6C(1) Seller Checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 274,
      y: 142,
      height: 9,
      width: 11,
    },
  },
  {
    id: "cbSurveySellerExistingReplacementBuyerExpense",
    name: "6C(1) Buyer Checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 325,
      y: 143,
      height: 9,
      width: 11,
    },
  },
  {
    id: "cbSurveyBuyerNew",
    name: "6C(2) Checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 57,
      y: 165,
      height: 9,
      width: 11,
    },
  },
  {
    id: "surveyBuyerNewDaysToDeliver",
    name: "6C(2) Number of Days",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 125,
      y: 165,
      height: 11,
      width: 36,
    },
  },
  {
    id: "cbSurveySellerNew",
    name: "6C(3) Checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 58,
      y: 198,
      height: 9,
      width: 11,
    },
  },
  {
    id: "surveySellerNewDaysToDeliver",
    name: "6C(3) Number of Days",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 124,
      y: 197,
      height: 11,
      width: 40,
    },
  },
  {
    id: "prohibitions6D",
    name: "6D Prohibitions on use or activity",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 118,
      y: 254,
      height: 10,
      width: 435,
    },
  },
  {
    id: "prohibitions6DDaysToObject",
    name: "6D(ii) Number of Days",
    type: "shortText",
    pageNum: 2,
    rect: {
      x: 371,
      y: 264,
      height: 9,
      width: 37,
    },
  },
  {
    id: "cbIsInHOA",
    name: "Is checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 453,
      y: 462,
      height: 9,
      width: 11,
    },
  },
  {
    id: "cbIsNotInHOA",
    name: "Is not checkbox",
    type: "checkbox",
    pageNum: 2,
    rect: {
      x: 476,
      y: 462,
      height: 9,
      width: 11,
    },
  },
  {
    id: "buyer1InitialPage359",
    name: "Buyer 1 Initial Page 3",
    type: "initial",
    pageNum: 2,
    rect: {
      x: 211,
      y: 757,
      height: 13,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage360",
    name: "Buyer 2 Initial Page 3",
    type: "initial",
    pageNum: 2,
    rect: {
      x: 254,
      y: 757,
      height: 13,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage361",
    name: "Seller 1 Initial Page 3",
    type: "initial",
    pageNum: 2,
    rect: {
      x: 347,
      y: 757,
      height: 13,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage362",
    name: "Seller 2 Initial Page 3",
    type: "initial",
    pageNum: 2,
    rect: {
      x: 396,
      y: 757,
      height: 13,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage4",
    name: "Address of Property Page 4",
    type: "shortText",
    pageNum: 3,
    rect: {
      x: 128,
      y: 29,
      height: 14,
      width: 326,
    },
  },
  {
    id: "titleRequiredNoticesLine1",
    name: "6E(11) Required Notices Line 1",
    type: "textWrap",
    pageNum: 3,
    children: [
      {
        name: "Line 1 - 6E(11) Required Notices Line 1",
        rect: {
          x: 295,
          y: 470,
          height: 10,
          width: 258,
        },
      },
      {
        name: "Line 2 - 6E(11) Required Notices Line 1",
        rect: {
          x: 88,
          y: 480,
          height: 9,
          width: 464,
        },
      },
      {
        name: "Line 3 - 6E(11) Required Notices Line 1",
        rect: {
          x: 90,
          y: 490,
          height: 10,
          width: 464,
        },
      },
    ],
  },
  {
    id: "cbBuyerHasReceivedSellerDisclosure",
    name: "7B(1) Buyer has received the Notice checkbox",
    type: "checkbox",
    pageNum: 3,
    rect: {
      x: 62,
      y: 590,
      height: 10,
      width: 11,
    },
  },
  {
    id: "cbBuyerHasNotReceivedSellerDisclosure",
    name: "7B(2) Buyer has not received the Notice checkbox",
    type: "checkbox",
    pageNum: 3,
    rect: {
      x: 62,
      y: 601,
      height: 10,
      width: 11,
    },
  },
  {
    id: "buyerHasNotReceivedSellerDisclosureDaysToDeliver",
    name: "7B(2) Number of Days",
    type: "shortText",
    pageNum: 3,
    rect: {
      x: 319,
      y: 602,
      height: 11,
      width: 49,
    },
  },
  {
    id: "cbSellerNotRequiredToDisclose",
    name: "7B(3) The Seller is not required to furnish the notice under the Texas Property Code",
    type: "checkbox",
    pageNum: 3,
    rect: {
      x: 62,
      y: 661,
      height: 9,
      width: 11,
    },
  },
  {
    id: "buyer1InitialPage470",
    name: "Buyer 1 Initial Page 4",
    type: "initial",
    pageNum: 3,
    rect: {
      x: 211,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage471",
    name: "Buyer 2 Initial Page 4",
    type: "initial",
    pageNum: 3,
    rect: {
      x: 253,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage472",
    name: "Seller 1 Initial Page 4",
    type: "initial",
    pageNum: 3,
    rect: {
      x: 347,
      y: 761,
      height: 10,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage573",
    name: "Seller 2 Initial Page 5",
    type: "initial",
    pageNum: 3,
    rect: {
      x: 397,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "propertyAddressPage5",
    name: "Address of Property Page 5",
    type: "shortText",
    pageNum: 4,
    rect: {
      x: 128,
      y: 30,
      height: 13,
      width: 326,
    },
  },
  {
    id: "cbBuyerAcceptsAsIs",
    name: "7D(1) Buyer accepts Property As Is Checkbox",
    type: "checkbox",
    pageNum: 4,
    rect: {
      x: 58,
      y: 61,
      height: 10,
      width: 11,
    },
  },
  {
    id: "cbBuyerAcceptsAsIsWithConditions",
    name: "7D(2) Buyer accepts Property As Is provided Seller … checkbox",
    type: "checkbox",
    pageNum: 4,
    rect: {
      x: 58,
      y: 73,
      height: 10,
      width: 11,
    },
  },
  {
    id: "buyerAcceptsAsIsWithConditionsDetailsLine1",
    name: "7D(2) Specific reparis and treatments",
    type: "textWrap",
    pageNum: 4,
    children: [
      {
        name: "Line 1 - 7D(2) Specific reparis and treatments",
        rect: {
          x: 302,
          y: 86,
          height: 10,
          width: 251,
        },
      },
      {
        name: "Line 2 - 7D(2) Specific reparis and treatments",
        rect: {
          x: 90,
          y: 96,
          height: 10,
          width: 464,
        },
      },
    ],
  },
  {
    id: "serviceContractReimbursementAmount",
    name: "7H Amount",
    type: "shortText",
    pageNum: 4,
    rect: {
      x: 422,
      y: 385,
      height: 11,
      width: 92,
    },
  },
  {
    id: "brokerDisclosureLine1",
    name: "8A Brokers and Sales Agent Disclosure Line 1",
    type: "textWrap",
    pageNum: 4,
    children: [
      {
        name: "Line 1 - 8A Brokers and Sales Agent Disclosure Line 1",
        rect: {
          x: 388,
          y: 493,
          height: 10,
          width: 164,
        },
      },
      {
        name: "Line 2 - 8A Brokers and Sales Agent Disclosure Line 1",
        rect: {
          x: 82,
          y: 505,
          height: 10,
          width: 469,
        },
      },
    ],
  },
  {
    id: "closingDayAndMonth",
    name: "9A Closing Day and Month",
    type: "shortText",
    pageNum: 4,
    rect: {
      x: 291,
      y: 549,
      height: 10,
      width: 131,
    },
  },
  {
    id: "closingYearLastTwoDigits",
    name: "9A Closing Year Last Two Digits",
    type: "shortText",
    pageNum: 4,
    rect: {
      x: 442,
      y: 549,
      height: 10,
      width: 27,
    },
  },
  {
    id: "buyer1InitialPage584",
    name: "Buyer 1 Initial Page 5",
    type: "initial",
    pageNum: 4,
    rect: {
      x: 211,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage585",
    name: "Buyer 2 Initial Page 5",
    type: "initial",
    pageNum: 4,
    rect: {
      x: 253,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage586",
    name: "Seller 1 Initial Page 5",
    type: "initial",
    pageNum: 4,
    rect: {
      x: 347,
      y: 761,
      height: 10,
      width: 41,
    },
  },
  {
    id: "587-0",
    name: "Seller 2 Initial Page 5",
    type: "initial",
    pageNum: 4,
    rect: {
      x: 396,
      y: 759,
      height: 10,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage6",
    name: "Address of Property Page 6",
    type: "shortText",
    pageNum: 5,
    rect: {
      x: 129,
      y: 31,
      height: 12,
      width: 326,
    },
  },
  {
    id: "cbBuyerPossessionAtCloseAndFund",
    name: "10A upon closing and funding",
    type: "checkbox",
    pageNum: 5,
    rect: {
      x: 351,
      y: 77,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbBuyerPossessionAfterTemporaryLease",
    name: "10A according to a temporary residential lease",
    type: "checkbox",
    pageNum: 5,
    rect: {
      x: 499,
      y: 77,
      height: 9,
      width: 10,
    },
  },
  {
    id: "specialProvisionsLine1",
    name: "11 Special Provisions Line 1",
    type: "textWrap",
    pageNum: 5,
    children: [
      {
        name: "Line 1 - 11 Special Provisions Line 1",
        rect: {
          x: 350,
          y: 302,
          height: 11,
          width: 205,
        },
      },
      {
        name: "Line 2 - 11 Special Provisions Line 1",
        rect: {
          x: 60,
          y: 313,
          height: 11,
          width: 495,
        },
      },
      {
        name: "Line 3 - 11 Special Provisions Line 1",
        rect: {
          x: 60,
          y: 323,
          height: 11,
          width: 495,
        },
      },
    ],
  },
  {
    id: "sellerAdditionalExpense",
    name: "12A(1)(b) Amount",
    type: "shortText",
    pageNum: 5,
    rect: {
      x: 352,
      y: 415,
      height: 10,
      width: 85,
    },
  },
  {
    id: "buyer1InitialPage696",
    name: "Buyer 1 Initial Page 6",
    type: "initial",
    pageNum: 5,
    rect: {
      x: 211,
      y: 757,
      height: 13,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage697",
    name: "Buyer 2 Initial Page 6",
    type: "initial",
    pageNum: 5,
    rect: {
      x: 253,
      y: 758,
      height: 13,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage698",
    name: "Seller 1 Initial Page 6",
    type: "initial",
    pageNum: 5,
    rect: {
      x: 347,
      y: 758,
      height: 13,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage699",
    name: "Seller 2 Initial Page 6",
    type: "initial",
    pageNum: 5,
    rect: {
      x: 396,
      y: 759,
      height: 12,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage7",
    name: "Address of Property Page 7",
    type: "shortText",
    pageNum: 6,
    rect: {
      x: 129,
      y: 31,
      height: 12,
      width: 325,
    },
  },
  {
    id: "buyer1InitialPage7101",
    name: "Buyer 1 Initial Page 7",
    type: "initial",
    pageNum: 6,
    rect: {
      x: 211,
      y: 759,
      height: 13,
      width: 36,
    },
  },
  {
    id: "buyer2InitialPage7102",
    name: "Buyer 2 Initial Page 7",
    type: "initial",
    pageNum: 6,
    rect: {
      x: 251,
      y: 759,
      height: 13,
      width: 37,
    },
  },
  {
    id: "seller1InitialPage7103",
    name: "Seller 1 Initial Page 7",
    type: "initial",
    pageNum: 6,
    rect: {
      x: 345,
      y: 759,
      height: 13,
      width: 42,
    },
  },
  {
    id: "seller2InitialPage7104",
    name: "Seller 2 Initial Page 7",
    type: "initial",
    pageNum: 6,
    rect: {
      x: 394,
      y: 759,
      height: 13,
      width: 38,
    },
  },
  {
    id: "propertyAddressPage8",
    name: "Address of Property Page 8",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 129,
      y: 30,
      height: 13,
      width: 326,
    },
  },
  {
    id: "buyerStreetAddress",
    name: "21 Buyer Street Address",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 133,
      y: 80,
      height: 13,
      width: 161,
    },
  },
  {
    id: "sellerStreetAddress",
    name: "21 Seller Street Address",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 386,
      y: 79,
      height: 14,
      width: 162,
    },
  },
  {
    id: "buyerCityStateZip",
    name: "21 Buyer City State Zip",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 62,
      y: 106,
      height: 14,
      width: 233,
    },
  },
  {
    id: "sellerCityStateZip",
    name: "21 Seller City State Zip",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 317,
      y: 106,
      height: 13,
      width: 232,
    },
  },
  {
    id: "buyerAreaCode",
    name: "21 Buyer Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 139,
      y: 130,
      height: 15,
      width: 22,
    },
  },
  {
    id: "buyerPhoneNumber",
    name: "21 Buyer Phone Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 166,
      y: 131,
      height: 14,
      width: 129,
    },
  },
  {
    id: "sellerAreaCode",
    name: "21 Seller Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 394,
      y: 129,
      height: 16,
      width: 21,
    },
  },
  {
    id: "sellerPhoneNumber",
    name: "21 Seller Phone Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 421,
      y: 129,
      height: 16,
      width: 128,
    },
  },
  {
    id: "buyerEmailFax1",
    name: "21 Buyer Email/Fax 1",
    type: "email",
    pageNum: 7,
    rect: {
      x: 135,
      y: 156,
      height: 14,
      width: 160,
    },
  },
  {
    id: "sellerEmailFax1",
    name: "21 Seller Email/Fax 1",
    type: "email",
    pageNum: 7,
    rect: {
      x: 388,
      y: 157,
      height: 13,
      width: 162,
    },
  },
  {
    id: "buyerEmailFax2",
    name: "21 Buyer Email/Fax 2",
    type: "email",
    pageNum: 7,
    rect: {
      x: 133,
      y: 181,
      height: 14,
      width: 162,
    },
  },
  {
    id: "sellerEmailFax2",
    name: "21 Seller Email/Fax 2",
    type: "email",
    pageNum: 7,
    rect: {
      x: 387,
      y: 180,
      height: 15,
      width: 162,
    },
  },
  {
    id: "buyerAgentInfo",
    name: "21 Buyer Agent Information",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 60,
      y: 212,
      height: 14,
      width: 235,
    },
  },
  {
    id: "sellerAgentInfo",
    name: "21 Seller Agent Information",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 316,
      y: 212,
      height: 15,
      width: 233,
    },
  },
  {
    id: "cbThirdPartyAddendumAttached",
    name: "22 Third Party Financing Addendum Checkbox",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 63,
      y: 271,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbSellerTempLeaseAttached",
    name: "22 Seller's Temporary Residential Lease Checkbox",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 315,
      y: 273,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbSellerFinancingAddendumAttached",
    name: "22 Seller Financing Addendum Checkbox",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 287,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbShortSaleAddendumAttached",
    name: "22 Short Sale Addendum Checkbox",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 314,
      y: 291,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbHOAAddendumAttached",
    name: "22 Addendum for Property Subject to Mandatory Membership in a Property Owners Association",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 301,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbGulfIntercoastalWaterwayAddendumAttached",
    name: "22 Addendum for Property Located Seaward of the Gulf Intracoastal Waterway",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 315,
      y: 309,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbBuyerTempLeaseAttached",
    name: "22 Buyers Temporary Residential Lease",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 334,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbLeadBasedPaintDisclosureAddendumAttached",
    name: "22 Addendum for Seller's Disclosure of Information on Lead-based Paint and Lead-Based Paint Hazards as Required by Federal Law",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 314,
      y: 336,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbLoanAssumptionAddendumAttached",
    name: "22 Loan Assumption Addendum",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 65,
      y: 349,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbSaleOfOtherPropertyAddendumAttached",
    name: "22 Addendum for Sale of Other Property by Buyer",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 65,
      y: 363,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbMineralRightReservationAttached",
    name: "22 Addendum for Reservation of Oil Gas and Other Minerals",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 65,
      y: 388,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbPropaneServiceAreaAddendumAttached",
    name: "22 Addendum for Property in a Propane Gas System Service Area",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 313,
      y: 381,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbAddendumForBackupContractAttached",
    name: '22 Addendum for "Back-Up" Contract',
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 66,
      y: 411,
      height: 10,
      width: 10,
    },
  },
  {
    id: "cbResidentialLeaseAddendumAttached",
    name: "22 Addendum Regarding Residential Leases",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 316,
      y: 403,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbFixtureLeaseAddendumAttached",
    name: "22 Addendum Regarding Fixture Leases",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 315,
      y: 419,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbCoastalPropertyAddendumAttached",
    name: "22 Addendum for Coastal Area Property",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 428,
      height: 9,
      width: 11,
    },
  },
  {
    id: "cbHydrostaticTestingAddendumAttached",
    name: "22 Addendum for Authorizing Hydrostatic Testing",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 65,
      y: 447,
      height: 11,
      width: 12,
    },
  },
  {
    id: "cbImprovementDistrictAddendumAttached",
    name: "22 Addendum Containing Notice of Obligation to Pay Inmprovment District Assessment",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 317,
      y: 440,
      height: 10,
      width: 11,
    },
  },
  {
    id: "cbRightToTerminateByLenderApprovalAddendumAttached",
    name: "22 Addendum Concerning Right to Terminate Due to Lender’s Appraisal",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 472,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbOtherAddendum",
    name: "22 Other",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 316,
      y: 468,
      height: 10,
      width: 11,
    },
  },
  {
    id: "otherAddendumDetailLine1",
    name: "22 Other Line 1",
    type: "textWrap",
    pageNum: 7,
    children: [
      {
        name: "Line 1 - 22 Other Line 1",
        rect: {
          x: 399,
          y: 467,
          height: 10,
          width: 156,
        },
      },
      {
        name: "Line 2 - 22 Other Line 1",
        rect: {
          x: 335,
          y: 478,
          height: 10,
          width: 219,
        },
      },
      {
        name: "Line 3 - 22 Other Line 1",
        rect: {
          x: 335,
          y: 490,
          height: 10,
          width: 219,
        },
      },
      {
        name: "Line 4 - 22 Other Line 1",
        rect: {
          x: 335,
          y: 500,
          height: 10,
          width: 219,
        },
      },
    ],
  },
  {
    id: "cbEnvironmentalAssesmentAddendumAttached",
    name: "22 Environmental Assessment Addendum",
    type: "checkbox",
    pageNum: 7,
    rect: {
      x: 64,
      y: 494,
      height: 10,
      width: 12,
    },
  },
  {
    id: "buyerAttorneyName",
    name: "23 Buyer Attorney Name",
    type: "fullName",
    pageNum: 7,
    rect: {
      x: 130,
      y: 577,
      height: 15,
      width: 169,
    },
  },
  {
    id: "sellerAttorneyName",
    name: "23 Seller Attorney Name",
    type: "fullName",
    pageNum: 7,
    rect: {
      x: 387,
      y: 577,
      height: 14,
      width: 174,
    },
  },
  {
    id: "buyerAttorneyAddress",
    name: "23 Buyer Attorney Address",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 67,
      y: 610,
      height: 15,
      width: 233,
    },
  },
  {
    id: "sellerAttorneyAddress",
    name: "23 Seller Attorney Address",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 323,
      y: 609,
      height: 16,
      width: 238,
    },
  },
  {
    id: "buyerAttorneyAreaCode",
    name: "23 Buyer Attorney Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 136,
      y: 651,
      height: 15,
      width: 23,
    },
  },
  {
    id: "buyerAttorneyPhoneNumber",
    name: "23 Buyer Attorney Phone Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 163,
      y: 651,
      height: 14,
      width: 137,
    },
  },
  {
    id: "sellerAttorneyAreaCode",
    name: "23 Seller Attorney Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 393,
      y: 651,
      height: 14,
      width: 23,
    },
  },
  {
    id: "sellerAttorneyPhoneNumber",
    name: "23 Seller Attorney Phone Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 419,
      y: 651,
      height: 15,
      width: 141,
    },
  },
  {
    id: "buyerAttorneyFaxAreaCode",
    name: "23 Buyer Attorney Fax Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 136,
      y: 692,
      height: 16,
      width: 23,
    },
  },
  {
    id: "buyerAttorneyFaxNumber",
    name: "23 Buyer Attorney Fax Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 163,
      y: 693,
      height: 14,
      width: 137,
    },
  },
  {
    id: "sellerAttorneyFaxAreaCode",
    name: "23 Seller Attorney Fax Area Code",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 393,
      y: 692,
      height: 15,
      width: 23,
    },
  },
  {
    id: "sellerAttorneyFaxNumber",
    name: "23 Seller Attorney Fax Number",
    type: "shortText",
    pageNum: 7,
    rect: {
      x: 419,
      y: 692,
      height: 16,
      width: 141,
    },
  },
  {
    id: "buyerAttorneyEmail",
    name: "23 Buyer Attorney Email",
    type: "email",
    pageNum: 7,
    rect: {
      x: 130,
      y: 733,
      height: 16,
      width: 169,
    },
  },
  {
    id: "sellerAttorneyEmail",
    name: "23 Seller Attorney Email",
    type: "email",
    pageNum: 7,
    rect: {
      x: 387,
      y: 733,
      height: 16,
      width: 174,
    },
  },
  {
    id: "buyer1InitialPage8159",
    name: "Buyer 1 Initial Page 8",
    type: "initial",
    pageNum: 7,
    rect: {
      x: 211,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "buyer2InitialPage8160",
    name: "Buyer 2 Initial Page 8",
    type: "initial",
    pageNum: 7,
    rect: {
      x: 254,
      y: 761,
      height: 10,
      width: 35,
    },
  },
  {
    id: "seller1InitialPage8161",
    name: "Seller 1 Initial Page 8",
    type: "initial",
    pageNum: 7,
    rect: {
      x: 346,
      y: 762,
      height: 10,
      width: 41,
    },
  },
  {
    id: "seller2InitialPage8162",
    name: "Seller 2 Initial Page 8",
    type: "initial",
    pageNum: 7,
    rect: {
      x: 396,
      y: 762,
      height: 10,
      width: 36,
    },
  },
  {
    id: "propertyAddressPage9",
    name: "Address of Property Page 9",
    type: "shortText",
    pageNum: 8,
    rect: {
      x: 129,
      y: 29,
      height: 15,
      width: 326,
    },
  },
  {
    id: "contractExecutionDay",
    name: "Executed Day",
    type: "shortText",
    pageNum: 8,
    rect: {
      x: 149,
      y: 223,
      height: 14,
      width: 38,
    },
  },
  {
    id: "contractExecutionMonth",
    name: "Executed Month",
    type: "shortText",
    pageNum: 8,
    rect: {
      x: 224,
      y: 225,
      height: 12,
      width: 137,
    },
  },
  {
    id: "contractExecutionYearLastTwoDigits",
    name: "Executed Year Last Two Digits",
    type: "shortText",
    pageNum: 8,
    rect: {
      x: 382,
      y: 224,
      height: 12,
      width: 27,
    },
  },
  {
    id: "buyer1Signature168",
    name: "Buyer 1 Signature",
    type: "signature",
    pageNum: 8,
    rect: {
      x: 72,
      y: 379,
      height: 32,
      width: 226,
    },
  },
  {
    id: "seller1Signature169",
    name: "Seller 1 Signature",
    type: "signature",
    pageNum: 8,
    rect: {
      x: 314,
      y: 379,
      height: 32,
      width: 232,
    },
  },
  {
    id: "buyer2Signature166",
    name: "Buyer 2 Signature",
    type: "signature",
    pageNum: 8,
    rect: {
      x: 72,
      y: 488,
      height: 32,
      width: 226,
    },
  },
  {
    id: "seller2Signature167",
    name: "Seller 2 Signature",
    type: "signature",
    pageNum: 8,
    rect: {
      x: 314,
      y: 488,
      height: 32,
      width: 232,
    },
  },
  {
    id: "propertyAddressPage10",
    name: "Address of Property Page 10",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 126,
      y: 28,
      height: 16,
      width: 326,
    },
  },
  {
    id: "otherBrokerFirmName",
    name: "Other Broker Firm",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 50,
      y: 150,
      height: 14,
      width: 177,
    },
  },
  {
    id: "otherBrokerLicenseNumber",
    name: "License No",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 228,
      y: 150,
      height: 14,
      width: 59,
    },
  },
  {
    id: "listingBrokerFirmName",
    name: "Listing Broker Firm",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 149,
      height: 14,
      width: 197,
    },
  },
  {
    id: "listingBrokerLicenseNumber",
    name: "License No_4",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 504,
      y: 149,
      height: 14,
      width: 58,
    },
  },
  {
    id: "cbOtherBrokerRepresentsOnlyBuyer",
    name: "Buyer only as Buyer’s agent checkbox",
    type: "checkbox",
    pageNum: 9,
    rect: {
      x: 108,
      y: 184,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbListingBrokerRepresentsBuyerAndSeller",
    name: "Seller and Buyer as an intermediary",
    type: "checkbox",
    pageNum: 9,
    rect: {
      x: 363,
      y: 184,
      height: 10,
      width: 12,
    },
  },
  {
    id: "cbOtherBrokerIsSubagentOfListingAgent",
    name: "Seller as List Broker's subagent checkbox",
    type: "checkbox",
    pageNum: 9,
    rect: {
      x: 108,
      y: 199,
      height: 9,
      width: 12,
    },
  },
  {
    id: "cbListingBrokerRepresentsOnlySeller",
    name: "Seller only as Sellers agent",
    type: "checkbox",
    pageNum: 9,
    rect: {
      x: 362,
      y: 198,
      height: 9,
      width: 12,
    },
  },
  {
    id: "otherBrokerAssociateName",
    name: "Associates Name",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 50,
      y: 216,
      height: 15,
      width: 177,
    },
  },
  {
    id: "otherBrokerAssociateLicenseNumber",
    name: "License No_2",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 229,
      y: 216,
      height: 15,
      width: 58,
    },
  },
  {
    id: "listingBrokerAssociateName",
    name: "List Assoc Name",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 305,
      y: 216,
      height: 16,
      width: 191,
    },
  },
  {
    id: "listingBrokerAssociateLicenseNumber",
    name: "License No_5",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 498,
      y: 215,
      height: 16,
      width: 64,
    },
  },
  {
    id: "otherBrokerAssociateTeamName",
    name: "Team Name 0",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 49,
      y: 247,
      height: 15,
      width: 238,
    },
  },
  {
    id: "listingBrokerAssociateTeamName",
    name: "Listing Associate's Name",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 305,
      y: 247,
      height: 15,
      width: 258,
    },
  },
  {
    id: "otherBrokerAssociateEmail",
    name: "Associate's Email Address",
    type: "email",
    pageNum: 9,
    rect: {
      x: 50,
      y: 277,
      height: 15,
      width: 164,
    },
  },
  {
    id: "otherBrokerAssociatePhoneNumber",
    name: "Phone",
    type: "phone",
    pageNum: 9,
    rect: {
      x: 216,
      y: 276,
      height: 15,
      width: 72,
    },
  },
  {
    id: "listingBrokerAssociateEmailAddress",
    name: "Listing Associate's Email Address",
    type: "email",
    pageNum: 9,
    rect: {
      x: 305,
      y: 275,
      height: 17,
      width: 183,
    },
  },
  {
    id: "listingBrokerAssociatePhoneNumber",
    name: "Phone_3",
    type: "phone",
    pageNum: 9,
    rect: {
      x: 490,
      y: 275,
      height: 17,
      width: 72,
    },
  },
  {
    id: "otherBrokerAssociateSupervisorName",
    name: "Licensed Supervisor of Associate",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 50,
      y: 304,
      height: 17,
      width: 177,
    },
  },
  {
    id: "otherBrokerAssociateSupervisorPhoneNumber",
    name: "License No_3",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 229,
      y: 304,
      height: 17,
      width: 59,
    },
  },
  {
    id: "listingBrokerAssociateSupervisorName",
    name: "Licensed Supervisor of Listing Associate",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 306,
      height: 16,
      width: 191,
    },
  },
  {
    id: "listingBrokerAssociateSupervisorPhoneNumber",
    name: "License No_6",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 498,
      y: 306,
      height: 17,
      width: 64,
    },
  },
  {
    id: "otherBrokerStreetAddress",
    name: "Other Broker's Address",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 50,
      y: 336,
      height: 15,
      width: 165,
    },
  },
  {
    id: "otherBrokerPhoneNumber",
    name: "Phone_2",
    type: "phone",
    pageNum: 9,
    rect: {
      x: 216,
      y: 336,
      height: 15,
      width: 71,
    },
  },
  {
    id: "listingBrokerStreetAddress",
    name: "Listing Brokers Office Address",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 336,
      height: 16,
      width: 182,
    },
  },
  {
    id: "listingBrokerPhoneNumber",
    name: "Phone_4",
    type: "phone",
    pageNum: 9,
    rect: {
      x: 489,
      y: 336,
      height: 16,
      width: 73,
    },
  },
  {
    id: "otherBrokerCity",
    name: "City",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 50,
      y: 365,
      height: 16,
      width: 127,
    },
  },
  {
    id: "otherBrokerState",
    name: "State",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 178,
      y: 365,
      height: 16,
      width: 44,
    },
  },
  {
    id: "otherBrokerZip",
    name: "Zip",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 222,
      y: 365,
      height: 16,
      width: 65,
    },
  },
  {
    id: "listingBrokerCity",
    name: "City_2",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 366,
      height: 15,
      width: 152,
    },
  },
  {
    id: "listingBrokerState",
    name: "State_2",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 458,
      y: 366,
      height: 15,
      width: 42,
    },
  },
  {
    id: "listingBrokerZip",
    name: "Zip_2",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 500,
      y: 366,
      height: 15,
      width: 61,
    },
  },
  {
    id: "sellingAssociateName",
    name: "Selling Associate's Name",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 305,
      y: 396,
      height: 16,
      width: 193,
    },
  },
  {
    id: "sellingAssociateLicenseNumber",
    name: "License No_7",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 499,
      y: 396,
      height: 16,
      width: 63,
    },
  },
  {
    id: "sellingAssociateTeamName",
    name: "Team Name",
    type: "fullName",
    pageNum: 9,
    rect: {
      x: 305,
      y: 424,
      height: 16,
      width: 257,
    },
  },
  {
    id: "sellingAssociateEmail",
    name: "Selling Associate's Email Address",
    type: "email",
    pageNum: 9,
    rect: {
      x: 305,
      y: 455,
      height: 16,
      width: 181,
    },
  },
  {
    id: "sellingAssociatePhoneNumber",
    name: "Phone_5",
    type: "phone",
    pageNum: 9,
    rect: {
      x: 488,
      y: 455,
      height: 16,
      width: 74,
    },
  },
  {
    id: "sellingAssociateSupervisorName",
    name: "Licensed Supervisor of Selling Associate",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 485,
      height: 15,
      width: 191,
    },
  },
  {
    id: "sellingAssociateSupervisorLicenseNumber",
    name: "License No_8",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 497,
      y: 485,
      height: 15,
      width: 64,
    },
  },
  {
    id: "sellingAssociateStreetAddress",
    name: "Selling Associate's Office Address",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 514,
      height: 15,
      width: 257,
    },
  },
  {
    id: "sellingAssociateCity",
    name: "City_3",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 305,
      y: 546,
      height: 16,
      width: 140,
    },
  },
  {
    id: "sellingAssociateState",
    name: "State_3",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 446,
      y: 546,
      height: 16,
      width: 47,
    },
  },
  {
    id: "sellingAssociateZip",
    name: "Zip_3",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 494,
      y: 546,
      height: 17,
      width: 67,
    },
  },
  {
    id: "listingBrokerToOtherBrokerFeeLine1",
    name: "Fee Amount",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 433,
      y: 631,
      height: 10,
      width: 125,
    },
  },
  {
    id: "listingBrokerToOtherBrokerFeeLine2",
    name: "Fee Amount 1",
    type: "shortText",
    pageNum: 9,
    rect: {
      x: 52,
      y: 641,
      height: 11,
      width: 204,
    },
  },
  {
    id: "propertyAddressPage11",
    name: "Address of Property Page 11",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 127,
      y: 28,
      height: 16,
      width: 326,
    },
  },
  {
    id: "optionFeeReceiptAmount",
    name: "Amount (Option Fee)",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 107,
      y: 95,
      height: 16,
      width: 109,
    },
  },
  {
    id: "optionFeeReceiptPaymentForm",
    name: "Form of Payment 0",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 344,
      y: 96,
      height: 16,
      width: 212,
    },
  },
  {
    id: "optionFeeReceiptEscrowAgentName",
    name: "Escrow Agent Name 0",
    type: "fullName",
    pageNum: 10,
    rect: {
      x: 52,
      y: 132,
      height: 16,
      width: 248,
    },
  },
  {
    id: "optionFeeReceiptDate",
    name: "Date",
    type: "date",
    pageNum: 10,
    rect: {
      x: 313,
      y: 132,
      height: 16,
      width: 243,
    },
  },
  {
    id: "earnestMoneyReceiptAmount",
    name: "Amount (Earnest Money)",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 106,
      y: 181,
      height: 14,
      width: 115,
    },
  },
  {
    id: "earnestMoneyReceiptPaymentForm",
    name: "Form of Payment 1",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 359,
      y: 182,
      height: 14,
      width: 198,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowAgentName",
    name: "Escrow Agent Name",
    type: "fullName",
    pageNum: 10,
    rect: {
      x: 52,
      y: 207,
      height: 16,
      width: 130,
    },
  },
  {
    id: "earnestMoneyReceiptReceivedBy",
    name: "Received by",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 183,
      y: 207,
      height: 16,
      width: 117,
    },
  },
  {
    id: "earnestMoneyReceiptEmail",
    name: "Email Address",
    type: "email",
    pageNum: 10,
    rect: {
      x: 313,
      y: 207,
      height: 16,
      width: 140,
    },
  },
  {
    id: "earnestMoneyReceiptDate",
    name: "Date/Time",
    type: "date",
    pageNum: 10,
    rect: {
      x: 456,
      y: 207,
      height: 16,
      width: 100,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowStreetAddress",
    name: "Address",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 233,
      height: 16,
      width: 307,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowPhoneNumber",
    name: "Phone_6",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 233,
      height: 16,
      width: 189,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowCity",
    name: "City_4",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 257,
      height: 16,
      width: 163,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowState",
    name: "State_4",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 217,
      y: 257,
      height: 16,
      width: 40,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowZip",
    name: "Zip_4",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 258,
      y: 257,
      height: 16,
      width: 101,
    },
  },
  {
    id: "earnestMoneyReceiptEscrowFaxNumber",
    name: "Fax",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 257,
      height: 16,
      width: 189,
    },
  },
  {
    id: "contractReceiptEscrowAgentName",
    name: "Escrow Agent Name (Contract Receipt)",
    type: "fullName",
    pageNum: 10,
    rect: {
      x: 52,
      y: 330,
      height: 16,
      width: 134,
    },
  },
  {
    id: "contractReceiptReceivedBy",
    name: "Received by_2",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 189,
      y: 330,
      height: 16,
      width: 112,
    },
  },
  {
    id: "contractReceiptEscrowEmail",
    name: "Email Address_2",
    type: "email",
    pageNum: 10,
    rect: {
      x: 313,
      y: 330,
      height: 16,
      width: 148,
    },
  },
  {
    id: "contractReceiptEscrowDate",
    name: "Date_2",
    type: "date",
    pageNum: 10,
    rect: {
      x: 463,
      y: 330,
      height: 16,
      width: 93,
    },
  },
  {
    id: "contractReceiptEscrowStreetAddress",
    name: "Address_2",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 355,
      height: 16,
      width: 307,
    },
  },
  {
    id: "contractReceiptEscrowPhoneNumber",
    name: "Phone_7",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 355,
      height: 16,
      width: 189,
    },
  },
  {
    id: "contractReceiptEscrowCity",
    name: "City_5",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 379,
      height: 16,
      width: 162,
    },
  },
  {
    id: "contractReceiptEscrowState",
    name: "State_5",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 215,
      y: 379,
      height: 16,
      width: 40,
    },
  },
  {
    id: "contractReceiptEscrowZip",
    name: "Zip_5",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 258,
      y: 379,
      height: 16,
      width: 101,
    },
  },
  {
    id: "contractReceiptEscrowFaxNumber",
    name: "Fax_2",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 379,
      height: 16,
      width: 189,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptAmount",
    name: "Amount (Additional Earnest Money Receipt)",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 109,
      y: 435,
      height: 13,
      width: 104,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptPaymentForm",
    name: "Form of Payment",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 399,
      y: 435,
      height: 12,
      width: 161,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptEscrowAgentName",
    name: "Escrow Agent_3",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 459,
      height: 16,
      width: 126,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptReceivedBy",
    name: "Received by_3",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 180,
      y: 459,
      height: 16,
      width: 120,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptEmail",
    name: "Email Address_3",
    type: "email",
    pageNum: 10,
    rect: {
      x: 313,
      y: 459,
      height: 16,
      width: 150,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptDate",
    name: "DateTime_2",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 465,
      y: 459,
      height: 16,
      width: 91,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptStreetAddress",
    name: "Address_3",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 486,
      height: 16,
      width: 307,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptPhoneNumber",
    name: "Phone_8",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 486,
      height: 16,
      width: 189,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptCity",
    name: "City_6",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 52,
      y: 509,
      height: 15,
      width: 160,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptState",
    name: "State_6",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 214,
      y: 509,
      height: 15,
      width: 42,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptZip",
    name: "Zip_6",
    type: "shortText",
    pageNum: 10,
    rect: {
      x: 258,
      y: 509,
      height: 15,
      width: 101,
    },
  },
  {
    id: "additionalEarnestMoneyReceiptFaxNumber",
    name: "Fax_3",
    type: "phone",
    pageNum: 10,
    rect: {
      x: 368,
      y: 509,
      height: 17,
      width: 189,
    },
  },
];

export const allHOAAddendumFields: IPDFField[] = [
  {
    id: "propertyAddressStreetAndCity",
    name: "Street Address and City",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 36,
      y: 122,
      height: 13,
      width: 540,
    },
  },
  {
    id: "hoaNameAndPhoneNumber",
    name: "Name of Property Owners Association Association and Phone Number",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 36,
      y: 147,
      height: 13,
      width: 540,
    },
  },
  {
    id: "policyBySeller",
    name: "1 Within",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 44,
      y: 228,
      height: 8,
      width: 10,
    },
  },
  {
    id: "policyBySellerDaysToDeliver",
    name: "the Subdivision Information to the Buyer If Seller delivers the Subdivision Information Buyer may terminate",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 102,
      y: 227,
      height: 12,
      width: 72,
    },
  },
  {
    id: "policyByBuyer",
    name: "undefined",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 44,
      y: 284,
      height: 9,
      width: 10,
    },
  },
  {
    id: "policyByBuyerDaysToDeliver",
    name: "copy of the Subdivision Information to the Seller",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 101,
      y: 284,
      height: 11,
      width: 72,
    },
  },
  {
    id: "policyAlreadyReceived",
    name: "3Buyer has received and approved the Subdivision Information before signing the contract Buyer",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 44,
      y: 348,
      height: 9,
      width: 10,
    },
  },
  {
    id: "policyRequiresUpdatedResaleCert",
    name: "does",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 533,
      y: 349,
      height: 8,
      width: 9,
    },
  },
  {
    id: "policyDoesNotRequireUpdatedResaleCert",
    name: "does not require an updated resale certificate If Buyer requires an updated resale certificate Seller at",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 70,
      y: 358,
      height: 10,
      width: 10,
    },
  },
  {
    id: "policyNotNeeded",
    name: "4Buyer does not require delivery of the Subdivision Information",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 44,
      y: 399,
      height: 10,
      width: 10,
    },
  },
  {
    id: "transferFeesPaidByBuyer",
    name: "D DEPOSITS FOR RESERVES Buyer shall pay any deposits for reserves required at closing by the Association",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 365,
      y: 491,
      height: 10,
      width: 90,
    },
  },
  {
    id: "addedInfoCostPaidByBuyer",
    name: "Buyer",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 227,
      y: 558,
      height: 10,
      width: 11,
    },
  },
  {
    id: "addedInfoCostPaidBySeller",
    name: "Seller shall pay the Title Company the cost of obtaining the",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 273,
      y: 559,
      height: 9,
      width: 13,
    },
  },
  {
    id: "signature113",
    name: "Signature1",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 45,
      y: 623,
      height: 23,
      width: 239,
    },
  },
  {
    id: "signature214",
    name: "Signature2",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 318,
      y: 624,
      height: 22,
      width: 240,
    },
  },
  {
    id: "signature315",
    name: "Signature3",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 44,
      y: 678,
      height: 22,
      width: 239,
    },
  },
  {
    id: "signature416",
    name: "Signature4",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 317,
      y: 677,
      height: 22,
      width: 239,
    },
  },
];

export const allThirdPartyFinanceAddendumFields: IPDFField[] = [
  {
    id: "propertyAddressStreetAndCity",
    name: "Street Address and City",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 55,
      y: 142,
      height: 14,
      width: 504,
    },
  },
  {
    id: "isConventionalLoan",
    name: "1 Conventional Financing",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 58,
      y: 225,
      height: 9,
      width: 9,
    },
  },
  {
    id: "isConventionalFirstMortgage",
    name: "1A(1)",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 86,
      y: 238,
      height: 10,
      width: 12,
    },
  },
  {
    id: "conventionalFirstPrincipal",
    name: "Principal Amount",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 374,
      y: 239,
      height: 11,
      width: 102,
    },
  },
  {
    id: "conventionalFirstNumberOfYears",
    name: "Number of Years",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 292,
      y: 250,
      height: 12,
      width: 38,
    },
  },
  {
    id: "conventionalFirstRate",
    name: "Percent 0",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 515,
      y: 250,
      height: 11,
      width: 29,
    },
  },
  {
    id: "conventionalFirstRateLength",
    name: " of Years 0",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 219,
      y: 262,
      height: 11,
      width: 45,
    },
  },
  {
    id: "conventionalFirstRateNotToExceed",
    name: "Percent 1",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 352,
      y: 271,
      height: 12,
      width: 41,
    },
  },
  {
    id: "isConventionalSecondMortgage",
    name: "1A(2)",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 88,
      y: 286,
      height: 9,
      width: 9,
    },
  },
  {
    id: "conventionalSecondPrincipal",
    name: "Amount 1",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 390,
      y: 287,
      height: 11,
      width: 87,
    },
  },
  {
    id: "conventionalSecondNumberOfYears",
    name: " of Years 1",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 303,
      y: 296,
      height: 12,
      width: 62,
    },
  },
  {
    id: "conventionalSecondRate",
    name: "Percent 2",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 101,
      y: 308,
      height: 11,
      width: 31,
    },
  },
  {
    id: "conventionalSecondRateLength",
    name: " of Years 2",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 267,
      y: 307,
      height: 11,
      width: 46,
    },
  },
  {
    id: "conventionalSecondRateNotToExceed",
    name: "Percent 3",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 403,
      y: 319,
      height: 11,
      width: 53,
    },
  },
  {
    id: "isVALoan",
    name: "1B",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 58,
      y: 333,
      height: 9,
      width: 9,
    },
  },
  {
    id: "vaPrincipal",
    name: "Amount 2",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 95,
      y: 344,
      height: 12,
      width: 95,
    },
  },
  {
    id: "vaNumberOfYears",
    name: " of Years 3",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 375,
      y: 343,
      height: 11,
      width: 48,
    },
  },
  {
    id: "isFHALoan",
    name: "1C",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 57,
      y: 367,
      height: 10,
      width: 12,
    },
  },
  {
    id: "fhaSection",
    name: "Section Number",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 281,
      y: 368,
      height: 11,
      width: 103,
    },
  },
  {
    id: "fhaPrincipal",
    name: "Amount 3",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 95,
      y: 379,
      height: 11,
      width: 106,
    },
  },
  {
    id: "fhaNumberOfYears",
    name: " of Years 4",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 114,
      y: 390,
      height: 11,
      width: 49,
    },
  },
  {
    id: "fhaRate",
    name: "Percent4",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 336,
      y: 390,
      height: 11,
      width: 44,
    },
  },
  {
    id: "fhaRateLength",
    name: " of Years 5",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 89,
      y: 400,
      height: 11,
      width: 40,
    },
  },
  {
    id: "fhaRateNotToExceed",
    name: "Percent 4",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 204,
      y: 411,
      height: 11,
      width: 39,
    },
  },
  {
    id: "isVAGuaranteedLoan",
    name: "1D",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 58,
      y: 425,
      height: 10,
      width: 9,
    },
  },
  {
    id: "vaGuaranteedPrincipal",
    name: "Amount 4",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 445,
      y: 425,
      height: 12,
      width: 106,
    },
  },
  {
    id: "vaGuaranteedNumberOfYears",
    name: " of Year 6",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 482,
      y: 436,
      height: 12,
      width: 39,
    },
  },
  {
    id: "vaGuaranteedRate",
    name: "Percent 5",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 225,
      y: 447,
      height: 12,
      width: 38,
    },
  },
  {
    id: "vaGuaranteedRateLength",
    name: " of Years 7",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 396,
      y: 447,
      height: 11,
      width: 39,
    },
  },
  {
    id: "vaGuaranteedRateNotToExceed",
    name: "Percent 6",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 86,
      y: 469,
      height: 12,
      width: 43,
    },
  },
  {
    id: "isUSDAGuaranteedLoan",
    name: "1E",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 58,
      y: 482,
      height: 9,
      width: 9,
    },
  },
  {
    id: "usdaPrincipal",
    name: "Amount 5",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 484,
      y: 482,
      height: 12,
      width: 70,
    },
  },
  {
    id: "usdaNumberOfYears",
    name: " of Years 8",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 480,
      y: 495,
      height: 11,
      width: 40,
    },
  },
  {
    id: "usdaRate",
    name: "Percent 7",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 228,
      y: 504,
      height: 11,
      width: 28,
    },
  },
  {
    id: "usdaRateLength",
    name: " of Years 9",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 391,
      y: 505,
      height: 11,
      width: 42,
    },
  },
  {
    id: "usdaRateNotToExceed",
    name: "Percent 8",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 514,
      y: 515,
      height: 11,
      width: 29,
    },
  },
  {
    id: "isReverseMortgageLoan",
    name: "1F",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 56,
      y: 539,
      height: 11,
      width: 12,
    },
  },
  {
    id: "reverseMortgagePrincipal",
    name: "Amount 6",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 411,
      y: 551,
      height: 12,
      width: 80,
    },
  },
  {
    id: "reverseMortgageRate",
    name: "Percent 9",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 451,
      y: 563,
      height: 11,
      width: 34,
    },
  },
  {
    id: "reverseMortgageNumberOfYears",
    name: " of Years 10",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 149,
      y: 573,
      height: 11,
      width: 42,
    },
  },
  {
    id: "reverseMortgageRateNotToExceed",
    name: "Percent 10",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 275,
      y: 586,
      height: 11,
      width: 26,
    },
  },
  {
    id: "reverseMortgageWillBeFHAInsured",
    name: "Will",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 527,
      y: 587,
      height: 9,
      width: 11,
    },
  },
  {
    id: "reverseMortgageWillNotBeFHAInsured",
    name: "will not",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 89,
      y: 601,
      height: 11,
      width: 11,
    },
  },
  {
    id: "isOtherFinancing",
    name: "1G",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 58,
      y: 616,
      height: 9,
      width: 8,
    },
  },
  {
    id: "otherFinancingLender",
    name: "Name of Lender",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 427,
      y: 614,
      height: 12,
      width: 127,
    },
  },
  {
    id: "otherFinancingPrincipal",
    name: "Amount 10",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 331,
      y: 626,
      height: 12,
      width: 70,
    },
  },
  {
    id: "otherFinancingNumberOfYears",
    name: " of Years 11",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 443,
      y: 625,
      height: 12,
      width: 39,
    },
  },
  {
    id: "otherFinancingRate",
    name: "Percent 12",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 213,
      y: 637,
      height: 12,
      width: 23,
    },
  },
  {
    id: "otherFinancingRateLength",
    name: " of Years",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 386,
      y: 637,
      height: 11,
      width: 34,
    },
  },
  {
    id: "otherFinancingRateNotToExceed",
    name: "Percent",
    type: "shortText",
    pageNum: 0,
    rect: {
      x: 264,
      y: 651,
      height: 11,
      width: 26,
    },
  },
  {
    id: "otherFinancingWaivesRightToTerminate",
    name: "Does",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 405,
      y: 650,
      height: 11,
      width: 11,
    },
  },
  {
    id: "otherFinancingDoesNotWaiveRightToTerminate",
    name: "does not",
    type: "checkbox",
    pageNum: 0,
    rect: {
      x: 448,
      y: 650,
      height: 11,
      width: 11,
    },
  },
  {
    id: "buyer1Initials37",
    name: "Buyer 1 Initials",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 205,
      y: 760,
      height: 11,
      width: 23,
    },
  },
  {
    id: "buyer2Initials38",
    name: "Buyer 2 Initials",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 237,
      y: 760,
      height: 11,
      width: 27,
    },
  },
  {
    id: "seller1Initials39",
    name: "Seller 1 Initials",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 326,
      y: 760,
      height: 11,
      width: 29,
    },
  },
  {
    id: "seller2Initials40",
    name: "Seller 2 Initials",
    type: "initial",
    pageNum: 0,
    rect: {
      x: 363,
      y: 760,
      height: 11,
      width: 27,
    },
  },
  {
    id: "propertyAddressPage2",
    name: "Address of Property",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 57,
      y: 49,
      height: 16,
      width: 498,
    },
  },
  {
    id: "isSubjectToBuyerApproval",
    name: "2A This contract is subject to Buyer obtaining Buyer Approval",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 84,
      y: 99,
      height: 9,
      width: 9,
    },
  },
  {
    id: "buyerApprovalDaysToNotifyOfFailure",
    name: " of Days",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 393,
      y: 110,
      height: 11,
      width: 37,
    },
  },
  {
    id: "isNotSubjectToBuyerApproval",
    name: "2A This contract is not subject to Buyer obtaining Buyer Approval",
    type: "checkbox",
    pageNum: 1,
    rect: {
      x: 84,
      y: 178,
      height: 11,
      width: 11,
    },
  },
  {
    id: "fhaVaLenderAppraisedValue",
    name: "Amount",
    type: "shortText",
    pageNum: 1,
    rect: {
      x: 76,
      y: 362,
      height: 10,
      width: 128,
    },
  },
  {
    id: "signature13",
    name: "Signature1",
    type: "signature",
    pageNum: 1,
    rect: {
      x: 56,
      y: 590,
      height: 32,
      width: 244,
    },
  },
  {
    id: "signature344",
    name: "Signature 3",
    type: "signature",
    pageNum: 1,
    rect: {
      x: 311,
      y: 589,
      height: 32,
      width: 239,
    },
  },
  {
    id: "signature243",
    name: "Signature 2",
    type: "signature",
    pageNum: 1,
    rect: {
      x: 55,
      y: 642,
      height: 32,
      width: 243,
    },
  },
  {
    id: "signature445",
    name: "Signature 4",
    type: "signature",
    pageNum: 1,
    rect: {
      x: 312,
      y: 642,
      height: 32,
      width: 239,
    },
  },
];

export const allLenderApprovalTerminationAddendumFields: IPDFField[] = [
  {
    id: "propertyAddressAndCity",
    name: "Property Address and City",
    type: "usAddress",
    pageNum: 0,
    rect: {
      x: 223,
      y: 124,
      height: 16,
      width: 353,
    },
  },
  {
    id: "terminationOptions",
    name: "Termination Options",
    type: "radioGroup",
    pageNum: 0,
    options: {
      "1WaiverBuyerWAivesBuyersRightToTerminateTheContractUnderParagraph2BOfThe1":
        "Waiver",
      "2PartialWaiverBuyerWAivesBuyersRightToTerminateTheContractUnderParagraph2B2":
        "Partial Waiver",
      "3Additional3": "Additional Right to Terminate",
    },
    children: [
      {
        name: "Waiver",
        rect: {
          x: 47,
          y: 239,
          height: 9,
          width: 10,
        },
      },
      {
        name: "Partial Waiver",
        rect: {
          x: 46,
          y: 319,
          height: 9,
          width: 11,
        },
      },
      {
        name: "Additional Right to Terminate",
        rect: {
          x: 46,
          y: 441,
          height: 11,
          width: 10,
        },
      },
    ],
  },
  {
    id: "terminationOpinionOfValueAmount",
    name: "Opinion of Value Amount",
    type: "dollar",
    pageNum: 0,
    rect: {
      x: 231,
      y: 380,
      height: 14,
      width: 102,
    },
  },
  {
    id: "terminationDaysAfterEffectiveDate",
    name: "Days After Effective Date",
    type: "integer",
    pageNum: 0,
    rect: {
      x: 65,
      y: 462,
      height: 11,
      width: 45,
    },
  },
  {
    id: "terminationAppraisedValueLessThan",
    name: "Appraised Value Less Than",
    type: "dollar",
    pageNum: 0,
    rect: {
      x: 125,
      y: 493,
      height: 12,
      width: 95,
    },
  },
  {
    id: "buyerSignature",
    name: "Buyer Signature",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 42,
      y: 571,
      height: 32,
      width: 254,
    },
  },
  {
    id: "sellerSignature",
    name: "Seller Signature",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 317,
      y: 572,
      height: 31,
      width: 241,
    },
  },
  {
    id: "buyerSignature1",
    name: "Buyer Signature",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 43,
      y: 637,
      height: 33,
      width: 254,
    },
  },
  {
    id: "sellerSignature1",
    name: "Seller Signature",
    type: "signature",
    pageNum: 0,
    rect: {
      x: 317,
      y: 637,
      height: 33,
      width: 240,
    },
  },
];
